SELECT * FROM `users` WHERE `email` IS NOT NULL;
SELECT `number`, `fio` FROM `certificates` WHERE `year` IS NULL;
UPDATE `certificates` SET `series`='BH', `number`=25444 WHERE `user_id`=7;
DELETE FROM `users` ORDER BY `id` DESC LIMIT 5;
SELECT MIN(`count_students`) FROM `organizations` WHERE `type_id`=5;
SELECT SUM(`rating`) FROM `practice` WHERE `practice_id` = 1888;
SELECT COUNT(*) FROM `organizations`;
SELECT * FROM `news` ORDER BY `created_at` LIMIT 10;
SELECT `phones`, `name` FROM `directors` WHERE `organization` LIKE 'ВУЗ%';
SELECT `publish_date`, `body` FROM `publishes` LIMIT 5;
SELECT COUNT(*) as `count`, `region_id` FROM `schools` GROUP BY `region_id`;